
// --- Generics in TypeScript ---
// Generics allow you to create reusable components that work with ANY type 
// while still retaining full TYPE SAFETY (unlike using 'any').

// <T> is a "Type Variable" (placeholder) that captures the type passed in.
// - Parameter 'item: T' accepts a value of type T
// - Return type 'T[]' guarantees an array containing elements of that exact same type T
function wrapInArray<T>(item: T): T[] {
    return [item];
}

// 1. Passing a string -> TypeScript automatically infers T as string -> returns string[]
const stringArray = wrapInArray("Generics function define here");
console.log("stringArray =>", stringArray);

// 2. Passing a number -> TypeScript automatically infers T as number -> returns number[]
const numberArray = wrapInArray(43);
console.log("numberArray =>", numberArray);

// 3. Passing an object -> TypeScript infers T as { flavor: string, price: number } -> returns object[]
const objectArray = wrapInArray({ flavor: "Ginger", price: 50 });
console.log("objectArray =>", objectArray);

// 4. You can also explicitly specify the type if needed:
const explicitArray = wrapInArray<string>("Explicit type string");
console.log("explicitArray =>", explicitArray);









/////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////

// here A & B is the datatypes of a, b
// tuple is used here to return multiple types of values
function pair<A, B> ( a: A, b: B ) : [A, B] {
    return [a, b]
}

console.log("pair => ", pair(1, "hello"))
console.log("pair => ", pair("Masala", "Chai"))
console.log("pair => ", pair({a: 1}, {b: 2}))



/////////////////////////////////////////
/////////////////////////////////////////

// Generic - 1. Types 2. Interface

interface Box<T> {
    contents: T
}

const box1: Box<string> = {
    contents: "Hello"
}

const box2: Box<number> = {
    contents: 10
}

const box3: Box<boolean> = {
    contents: true
}

const box4: Box<string[]> = {
    contents: ["Hello", "World"]
}

const box5: Box<number[]> = {
    contents: [1, 2, 3]
}

console.log("box1 => ", box1)
console.log("box2 => ", box2)
console.log("box3 => ", box3)
console.log("box4 => ", box4)
console.log("box5 => ", box5)

///////////////////////////////////
///////////////////////////////////
///////////////////////////////////

// --- Built-in Generic Utility Types: Partial, Required, Pick, Omit ---

// Base Interface for our example
interface ChaiOrder {
    id: number;
    flavor: string;
    price: number;
    sugar?: boolean; // Optional property
}

// 1. Partial<T> -> Makes ALL properties OPTIONAL (?)
// Useful when updating an existing order where you only send changed fields
const updateOrder: Partial<ChaiOrder> = {
    flavor: "Ginger" // id, price, and sugar are not required
};
console.log("Partial (updateOrder) =>", updateOrder);


// 2. Required<T> -> Makes ALL properties MANDATORY (removes ?)
// Even 'sugar' which was optional is now strictly required
const completeOrder: Required<ChaiOrder> = {
    id: 1,
    flavor: "Masala",
    price: 30,
    sugar: true // Must provide sugar!
};
console.log("Required (completeOrder) =>", completeOrder);


// 3. Pick<T, Keys> -> Selects ONLY the specified keys from T
// Useful when you need a smaller slice of an object (e.g. summary display)
type OrderSummary = Pick<ChaiOrder, "flavor" | "price">;

const summary: OrderSummary = {
    flavor: "Elaichi",
    price: 40
};
console.log("Pick (summary) =>", summary);


// 4. Omit<T, Keys> -> REMOVES specific keys and keeps everything else
// Useful for creating a new order before an 'id' is generated by the database
type NewChaiOrder = Omit<ChaiOrder, "id">;

const newOrder: NewChaiOrder = {
    flavor: "Kesar",
    price: 60,
    sugar: false
};
console.log("Omit (newOrder) =>", newOrder);


//////////////////////////////////////////////////
//////////////////////////////////////////////////
//////////////////////////////////////////////////
//////////////////////////////////////////////////

// real world example
// api usages
interface ApiPromise<T> {
    status: number
    data: T
    success: boolean
}

const res : ApiPromise< { flavor: string } > = {
    status: 200,
    data: {flavor: "Masala"},
    success: true
}

console.log("res => ", res)

const apiResult: ApiPromise<string> = {
    status: 200,
    data: "Hello",
    success: true
}

console.log("apiResult => ", apiResult)

const apiResult2: ApiPromise<{ name: string, age: number }> = {
    status: 200,
    data: { name: "John Doe", age: 30 },
    success: true
}

console.log("apiResult2 => ", apiResult2)

////////////////////////////////////////////////////
////////////////////////////////////////////////////
////////////////////////////////////////////////////
////////////////////////////////////////////////////

// function overloading


// here we are using 'any' type
function printValues(arg1: any, arg2: any): void {
    console.log(arg1, arg2);
}

printValues(10, "Hello");        // 10, Hello
printValues("Type", true);          // Type, true
printValues(3.14, [1, 2]);      // 3.14, [1, 2]
